### ISSUE TITLE
PHPDoc file headers

### ISSUE THREAD

**Issue by szepeviktor** [theofidry/console#61]
Would you welcome valid File-level DocBlocks?

```php
/**
 * @package           Fidry\Console
 * @author            Théo FIDRY <theo.fidry@gmail.com>
 * @copyright         2022 Théo FIDRY
 * @license           https://github.com/theofidry/console/blob/main/LICENSE MIT
 */
```

**Comment by theofidry** [comment]
Hi,

I would prefer not as they genuinely are not that relevant, the information is redundant with others, it's a bit annoying to keep in sync and I do not have them for any of my other projects either.

Thanks for proposing though :)

**Comment by szepeviktor** [comment]
> (unless there is real value)

I like following standards and keep my personal inventions out of the computer.

**Comment by theofidry** [comment]
I'm having a bit of trouble to follow.

- What value provides `@package`? On its own it may at best indicate the top level namespace (in which case it is redundant with the `namespace` declaration) but otherwise it is not even referring to the Composer package name (which can be different than the namespace name). To me, it comes off as an artifact from old PHP versions before PHP namespaces were introduced.
- I do like the `@author` when the file is created/edited by someone else, but the license is already mentioned. Symfony makes usage of it a lot for example
- copyright & license are already included as header files. Maybe it could be replaced in favour of this PHP annotations but at least in my case I've been using so much the previous ones, I don't think it's worth switching to something else

**Comment by szepeviktor** [comment]
> What value

Sorry. I'm not a businessman. I do things the best way I can in _my laboratory_.

It is possible that following phpDocumentor has no measurable value in this case.

**Comment by szepeviktor** [comment]
I'm almost 50 years old. Maybe an old man is used to his ways.

**Comment by theofidry** [comment]
Oh I did not mean _monetary_ value :) (I am no business man myself!). However like everything, changing things has a cost in time & efforts and they are always limited resources, hence trying to figure out if there is a real benefit from it.

>It is possible that following phpDocumentor has no measurable value in this case.

Ha it's been a very long time since I last checked/use phpDocumentor I admit! It might be a different story for some specific files, but I otherwise would expect those information to be picked from the `composer.json` in general (i.e. the default comes from there, then maybe a specific file might override some of this information differently). If it's not then I think it's missing out on that feature, because I don't think there is many people using all of those tags consistently in the PHP ecosystem.

>I'm almost 50 years old. Maybe an old man is used to his ways :(

Don't worry, I'm more in the middle but even youngsters can pick up habits very quickly ;)
